name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Push to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build --tag ghcr.io/sosuke-d-mahi/mphisher:latest .
          docker push ghcr.io/sosuke-d-mahi/mphisher:latest
        if: github.repository == 'sosuke-d-mahi/mphisher' && github.ref == 'refs/heads/master'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: "sosuke-d-mahi"
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.repository == 'sosuke-d-mahi/mphisher' && github.ref == 'refs/heads/master'

      - name: Build and Push to DockerHub
        run: |
          docker build --tag sosuke-d-mahi/mphisher:latest .
          docker push sosuke-d-mahi/mphisher:latest
        if: github.repository == 'sosuke-d-mahi/mphisher' && github.ref == 'refs/heads/master'

